spring:
  application:
    name: foodstore
  data:
    mongodb:
      #uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/foodstore
      uri: mongodb+srv://test:test@foodstore.gak0m.mongodb.net/foodstore?retryWrites=true&w=majority
      authentication-database: admin
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

jwt:
  secret: 9RLtDzsDcwb67990ssdq


paging:
  default:
    page: 0
    size: 20

file:
  download_dir: "./downloads"
  upload_dir: "./uploads"

google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=

logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/socialising
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7


kafka:
  bootstrap-servers: ${KAFKA_SERVERS:stc:9094}
  topic:
    email-no-template: email-no-template
    email-with-template: email-with-template
    email-with-attachment: email-with-attachment

twilio:
  account-sid: ACbfacc48411e45c587c9308aee50d4822
  account-password: 80ebe83ba28708aaf147070b60a27cc9
  account-from-number: +13254405996

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 1200000
  eager-load:
    enabled: true
    clients: service-bar

otp:
  ExpriedTime: 900

server:
  error:
    include-message: always
  port: 8080
